### ISSUE TITLE
Traitement des facteurs majeurs de gravité dans le cadre d'une prise en charge par un opérateur

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#1]
Dans l'algorithme, si 1 ou plus de facteurs de gravité majeurs sont présents, on redirige vers un numéro d'appel d'urgence (FIN 5, appelez le 15)

Comment traiter ces facteurs de gravité majeurs dans le cas où la personne est déjà au téléphone avec un opérateur de service d'urgence et que l'application est là pour aider l'opérateur ? Est-ce que la réponse positive à une de ses questions doit par exemple être converti en "envoi d'une ambulance" ?

Également, les facteurs retenus sont pertinents dans le cadre du COVID, mais une personne ayant ces symptômes peut appeler le 15 sans que ceux-ci soient liés au COVID (vieille personne s'alimentant peu par exemple).

En résumé, comment traiter et pondérer ces facteurs de gravités non pour une orientation vers un numéro d'urgence, mais pour aider un opérateur de service d'urgence à prendre une décision ?

**Comment by bzg** [comment]
> Dans l'algorithme, si 1 ou plus de facteurs de gravité majeurs sont présents, on redirige vers un numéro d'appel d'urgence (FIN 5, appelez le 15)

Note que dans la version actuelle de l'arbre, ce n'est le cas que si l'on est dans l'une de ces deux clauses:

> SI fièvre ET toux
> SI fièvre OU diarrhée OU (toux ET douleurs) OU (toux ET anosmie)

Pour cette question:

> Comment traiter ces facteurs de gravité majeurs dans le cas où la personne est déjà au téléphone avec un opérateur de service d'urgence et que l'application est là pour aider l'opérateur ? Est-ce que la réponse positive à une de ses questions doit par exemple être converti en "envoi d'une ambulance" ?

Je suppose qu'on peut faire imaginer avoir une première question sur le type de répondant et adapter les questions/réponses ensuite. A voir ensuite si ça doit être documenté et comment (dans ce dépôt, ailleurs, etc.)

> En résumé, comment traiter et pondérer ces facteurs de gravités non pour une orientation vers un numéro d'urgence, mais pour aider un opérateur de service d'urgence à prendre une décision ?

Même réponse ici... bonne question, mais il faudra que la cible de la documentation soit claire.

**Comment by bzg** [comment]
Note que le problème a resurgit.

**Comment by judbd** [comment]
Oui, tout juste quand je venais de commit ma nouvelle implémentation. Je vais attendre je crois 😄

**Comment by bzg** [comment]
Salut @judbd - je ferme cette issue qui n'est plus pertinente à ce stade, l'arbre de décision étant bien pour les solutions d'_auto_-évaluation.  Si d'autres applications se référent à cet arbre pour implémenter le cas où c'est un opérateur qui y est exposé, ils pourront adapter.
