### ISSUE TITLE
Comportement si > 1 facteur de gravité mineur

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#2]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/7f32d2154565bd3647487c72d16143c6bf3bd4d0/covid19-orientation-arbre-de-decision.txt#L6

Dans ce bloc :
```
SI fièvre ET toux
   SI >= 1 facteurs de gravité majeurs => FIN5
   SI 0 facteur pronostique
      SI 0 OU 1 facteur de gravité mineur => FIN6
```
 Si on a plus d'1 facteur de gravité mineurs (par ex 39 de fièvre et fatigue) Le résultat est "vous n'avez certainement pas le COVID" (message 9 par défaut) alors que si on a juste de la fièvre ça affiche le message 6 "consultez un médecin".

Il y a un problème de sortie à cet endroit, je pense qu'il faudrait mettre `SI 1 OU PLUS facteur de gravité mineur => FIN6`

**Comment by bzg** [comment]
Oui - j'ai entre-temps reçu un nouveau PDF avec un nouvel arbre de décision validé par les médecins... je suis en train de mettre à jour, j'enverrai un point par mail ce soir quand ce sera fait.
