### ISSUE TITLE
Critère de sortie en trop ?

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#4]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/16eddd731509aea3e8ac54df5d7d834564f46e91/covid19-orientation-arbre-de-decision.txt#L16

À quoi se réfère cette `FIN 3` ici ?

**Comment by bzg** [comment]
Au cas où il n'y a pas de facteur pronostique défavorable et au moins un facteur de gravité mineur - j'ai explicité, le pseudo-code n'était pas assez lisible. Merci !
