### ISSUE TITLE
Harmoniser la notation

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#5]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/16eddd731509aea3e8ac54df5d7d834564f46e91/covid19-orientation-arbre-de-decision.txt#L19

Choisir comment noter cette ligne, on peut adopter la notation `SI <= 2` utilisée précedemment, ou choisir celle-ci.

**Comment by bzg** [comment]
Oui, fait dans un précédent commit, merci !
