### ISSUE TITLE
Présentation de la condition

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#6]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/16eddd731509aea3e8ac54df5d7d834564f46e91/covid19-orientation-arbre-de-decision.txt#L7

On pourrait peut-être remplacer `SI 0 OU 1` par `SI < 2` ou `SI MOINS DE 2` pour plus de clarté ?

**Comment by bzg** [comment]
Oui - je suis parti sur `SI < 2` - merci !
