### ISSUE TITLE
Simplification de la condition ?

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#7]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/16eddd731509aea3e8ac54df5d7d834564f46e91/covid19-orientation-arbre-de-decision.txt#L22

Ici on a retiré la condition `SI 1 OU PLUS Facteur de gravité mineure OU 1 OU PLUS facteur de pronostic` qu'il y avait sur les versions précédentes ?

**Comment by bzg** [comment]
Oui, la simplification a été faite en amont dans le document envoyé par les médecins.
