### ISSUE TITLE
Disparition de l'absence de fièvre pour la sortie 9 ?

### ISSUE THREAD

**Issue by judbd** [Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision#8]
https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-arbre-de-decision/blob/16eddd731509aea3e8ac54df5d7d834564f46e91/covid19-orientation-arbre-de-decision.txt#L25

Nous avions anciennement une vérification d'absence de fièvre ici, mais peut-être est-ce inclus dans la sortie par défaut.

**Comment by bzg** [comment]
Oui, l'arbre reste séquentiel : s'il y a de la fièvre, la clause d'avant est vérifiée et celle-ci non.
